version: '3'

services:
  http-server:
    build: ./HttpServer
    ports:
      - '8000:8000'
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '54322:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      #- ../../HiLoadArchitect/postgres/:/var/lib/postgresql/data
      # copy the sql script to create tables
      #- ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

    #docker run --hostname=ccc693925079 --mac-address=02:42:ac:11:00:02 --env=PGDATA=/var/lib/postgresql/data/pgdata --env=POSTGRES_USER=postgres --env=POSTGRES_PASSWORD=postgres --env=POSTGRES_DB=postgres --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/15/bin --env=GOSU_VERSION=1.16 --env=LANG=en_US.utf8 --env=PG_MAJOR=15 --env=PG_VERSION=15.3-1.pgdg110+1 --volume=/home/igor/Work/HiLoadArchitect/postgres/:/var/lib/postgresql/data --volume=/var/lib/postgresql/data -p 5432:5432 --restart=no --runtime=runc -d postgres